name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # List your project directories here.
        # Each directory must contain a gradlew script and a Dockerfile.
        project: [ 'cash-card', 'projecto-dos' ] # <- Agrega aquí tus proyectos

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # This step assumes each project has its own Gradle Wrapper (gradlew).
    - name: Build with Gradle
      run: |
        cd ${{ matrix.project }}
        ./gradlew build

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.project }}
        file: ./${{ matrix.project }}/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.project }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.project }}:${{ github.sha }}
        # We add two tags: 'latest' and one with the commit SHA for versioning.
